"""baseline grandpa_yin product tables

Revision ID: a6e5ccf71d56
Revises: 
Create Date: 2026-07-21 21:22:02.874467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6e5ccf71d56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Product tables use `account_id` as a *logical* reference (plain UUID) with
    NO cross-schema FK to public.accounts, so a standalone DB can build without
    Altide. In platform mode the FK is added back by the later integration
    migration (platform_integration_account_fk).
    """
    # 本產品擁有的 schema；全新環境（尚未有 grandpa_yin schema）也能直接建起
    op.execute('CREATE SCHEMA IF NOT EXISTS grandpa_yin')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sessions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=False),
    sa.Column('state_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    schema='grandpa_yin'
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('feature_type', sa.Text(), nullable=False),
    sa.Column('points_deducted', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='grandpa_yin'
    )
    op.create_index(op.f('ix_grandpa_yin_usage_logs_account_id'), 'usage_logs', ['account_id'], unique=False, schema='grandpa_yin')
    op.create_table('user_profiles',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('preferred_nickname', sa.Text(), nullable=True),
    sa.Column('is_tutorial_completed', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    schema='grandpa_yin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles', schema='grandpa_yin')
    op.drop_index(op.f('ix_grandpa_yin_usage_logs_account_id'), table_name='usage_logs', schema='grandpa_yin')
    op.drop_table('usage_logs', schema='grandpa_yin')
    op.drop_table('bot_sessions', schema='grandpa_yin')
    # ### end Alembic commands ###
